# -*- coding: utf-8 -*-
"""treinamento_de_modelos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_jUoxFVWcmIbUT1LsALqRCY5kWAqK_F

📡 Previsão com dados da API usando modelo treinado

Neste trecho, os valores que podem vir de uma API são armazenados em variáveis simples (data_api, cota_api e chuva_api), facilitando a substituição direta por dados reais da API sem necessidade de conversão adicional. Em seguida, esses valores são organizados em um DataFrame, que é a estrutura esperada pelo modelo para fazer a previsão, o modelo e o scaler, previamente treinados e salvos, são carregados com joblib. O scaler é aplicado ao novo dado para normalizar as variáveis conforme o treinamento. Por fim, a previsão é feita pelo modelo, e o resultado numérico é convertido de volta para o valor categórico original com LabelEncoder.

Este fluxo permite receber dados diretamente da API, aplicar o modelo treinado e obter uma previsão interpretável de forma simples e organizada.
"""

# --- Importações necessárias ---
import pandas as pd
import joblib

# --- Valores que podem vir da API ---
data_api = 106
cota_api = 500
chuva_api = 14

# --- Criando DataFrame com variáveis simples, fácil de substituir por dados da API ---
novo_dado = pd.DataFrame({
    'Data': [data_api],
    'Cota': [cota_api],
    'Chuva': [chuva_api]
})

# --- Carregando modelo, scaler e label encoder salvos ---
nome_arquivo = 'modelos_salvos/GradBoost200.pkl'
dados = joblib.load(nome_arquivo)

modelo = dados['modelo']
scaler = dados['scaler']
le = dados['label_encoder']  # <--- Aqui está o carregamento do LabelEncoder

# --- Aplicando o scaler ao novo dado ---
novo_dado_scaled = scaler.transform(novo_dado)

# --- Fazendo a previsão ---
previsao = modelo.predict(novo_dado_scaled)

# --- Convertendo o resultado para a categoria original (texto) ---
previsao_texto = le.inverse_transform(previsao)

# --- Exibindo o resultado ---
print(f"Previsão: {previsao_texto[0]}")